### PR TITLE
LLVM bump 20220425

### PR DESCRIPTION
**Pull request by okkwon**
Integrate llvm-project and bump dependencies   
* llvm-project: a48300aee570
* mlir-hlo: ae579ab44f6cd34feec11f82447356cf9f9d5b0f
* tensorflow: fa5d2b36d097e5e2df5b487a5ac13efe62c41597

### CODE REVIEW

**Comment by antiagainst** [comment]
It looks there are [issues](https://source.cloud.google.com/results/invocations/d623dc56-03e4-4cd8-94a6-db44d8acd478/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-swiftshader%2Fpresubmit/log) with bufferization in linalg transform dialects: "Assertion `options.bufferizeFunctionBoundaries && "expected that function boundary bufferization is activated"' failed." The check was introduced in https://github.com/llvm/llvm-project/commit/d6dab38ae48a298b671107c9ebdd86de8f7cd482. @matthias-springer might be able to help here.

**Comment by matthias-springer** [comment]
This should be easy to fix. Add this line somewhere before `runOneShotModuleBufferize` in llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/LinalgTransformOps.cpp:

```
options.bufferizeFunctionBoundaries = true;
```

**Comment by okkwon** [comment]
Thanks Lei and Matthias. I will take a look.

**Review by antiagainst — APPROVED** [review]
LGTM. Feel free to land once all bots are happy. :)

**Comment by okkwon** [comment]
There are two failures I am looking into. But I feel the header is needed to build, but cmake_linux_x86-swiftshader complains:

```
llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/Transforms/TransformInterpreter.cpp:17:10: error: module //llvm-external-projects/iree-dialects:IREELinalgTransformDialectTransforms does not depend on a module exporting 'mlir/Dialect/Bufferization/Transforms/FuncBufferizableOpInterfaceImpl.h'
#include "mlir/Dialect/Bufferization/Transforms/FuncBufferizableOpInterfaceImpl.h"
         ^
1 error generated.
```

**Comment by okkwon** [comment]
@matthias-springer Hi Matthias, I keep getting build failure from cmake_linux_x86_swiftshader and bazel_linux_x86-swiftshader_core. Do you have any idea?

**Comment by okkwon** [comment]
Okay. The bazel issue is fixed. I had to add `mlir:BufferizationTransforms` as dependency in a `BUILD` file. The remaining issues seem to be related to tests. I am looking into them.

**Comment by okkwon** [comment]
@matthias-springer I think I need your help to resolve the issues with the test cases.

FileCheck fails because it cannot find the memref. The output of the iree-interp-transforms now keeps the original tensors instead of generating memref.

**Comment by okkwon** [comment]
Found another place to add the option. Fingers crossed.
