### ISSUE TITLE
Build failures with GCC

### ISSUE THREAD

**Issue by marbre** [google/iree#147]
I am aware that IREE is currently build with clang, however, I gave gcc 8.3.0 a try. After modifying `build_tools/cmake/iree_copts.cmake` to get rid of the error messages about unknown parameters, the build fails with the following errors:
```
~/Development/iree/iree/base/internal/status_macros.h:55:34: error: conflicting declaration ‘auto _status_or_value486’
       STATUS_MACROS_IMPL_CONCAT_(_status_or_value, __LINE__), lhs, rexpr,    \
                                  ^~~~~~~~~~~~~~~~

~/Development/iree/iree/vm/sequencer_dispatch.cc:485:9: error: invalid conversion from ‘iree::hal::BufferView*’ to ‘iree::device_size_t’ {aka ‘long unsigned int’} [-fpermissive]
         dst_offset, src_local->buffer.get(), src_offset, length));
         ^~~~~~~~~~

~/Development/iree/iree/vm/sequencer_dispatch.cc:485:46: error: invalid conversion from ‘iree::hal::BufferView*’ to ‘iree::device_size_t’ {aka ‘long unsigned int’} [-fpermissive]
         dst_offset, src_local->buffer.get(), src_offset, length));
                                              ^~~~~~~~~~

~/Development/iree/iree/vm/sequencer_dispatch.cc:485:58: error: invalid conversion from ‘iree::hal::BufferView*’ to ‘iree::device_size_t’ {aka ‘long unsigned int’} [-fpermissive]
         dst_offset, src_local->buffer.get(), src_offset, length));
                                                          ^~~~~~

~/Development/iree/iree/base/internal/status_macros.h:65:40: error: unable to deduce ‘auto*’ from ‘(& std::move<iree::StatusOr<int>&>(_status_or_value499))->iree::StatusOr<int>::ValueOrDie()’
   lhs = std::move(statusor).ValueOrDie()
                                        ^

~/Development/iree/iree/base/internal/status_macros.h:28:60: error: could not convert ‘{<expression error>, iree::SourceLocation::DoNotInvokeDirectly(((uint_least32_t)499), ((const char*)"~/Development/iree/iree/vm/sequencer_dispatch.cc"))}’ from ‘<brace-enclosed initializer list>’ to ‘iree::status_macro_internal::StatusAdaptorForMacros’
           status_macro_internal_adaptor = {(expr), IREE_LOC}) { \
                                                            ^

~/Development/iree/iree/base/internal/status_macros.h:65:40: error: no match for ‘operator=’ (operand types are ‘iree::ref_ptr<iree::hal::Buffer>’ and ‘iree::hal::BufferView*’)
   lhs = std::move(statusor).ValueOrDie()
                                        ^

~/Development/iree/iree/vm/sequencer_dispatch.cc:532:39: error: no matching function for call to ‘iree::Shape::Shape(<brace-enclosed initializer list>)’
     Shape new_shape = Shape{shape_data};
                                       ^
```
For convenience, I skipped the other error messages regarding the conflicting declaration in `status_macros.h:55:34`. Also if clang is the preferred compiler, these errors messages produced by gcc might be worth a look.

**Comment by ScottTodd** [comment]
``vm/sequencer_dispatch.cc`` doesn't compile under MSVC either, but we plan on replacing it (see the vm2/ folder)

The `status` errors are worth fixing.

**Comment by benvanik** [comment]
I think this is fine now (or, at least, this file was deleted so if there's still errors the are new ones :)
