### ISSUE TITLE
[spirv] Need to set static bound for dynamic allocations

### ISSUE THREAD

**Issue by powderluv** [google/iree#9322]
``` E         <stdin>:363:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spv.target_env = #spv.target_env<#spv.vce<v1.3, [Shader, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative], [SPV_KHR_storage_buffer_storage_class]>, SwiftShader:CPU, {cooperative_matrix_properties_nv = [], max_compute_shared_memory_size = 16384 : i32, max_compute_workgroup_invocations = 128 : i32, max_compute_workgroup_size = dense<[128, 128, 64]> : vector<3xi32>, subgroup_size = 4 : i32}>}>
E             %112 = linalg.generic {indexing_maps = [#map3, #map5, #map4], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%111, %cst_6 : tensor<?x1x1x?xf32>, tensor<f64>) outs(%110 : tensor<?x1x1x?xf32>) {
E                    ^
E         <stdin>:21:3: note: called from
E           func.func @forward(%arg0: tensor<?x?xi64>) -> tensor<?x2xf32> {
E           ^
E         <stdin>:363:12: error: failed to serialize executables
E             %112 = linalg.generic {indexing_maps = [#map3, #map5, #map4], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%111, %cst_6 : tensor<?x1x1x?xf32>, tensor<f64>) outs(%110 : tensor<?x1x1x?xf32>) {
E                    ^
E         <stdin>:21:3: note: called from
E           func.func @forward(%arg0: tensor<?x?xi64>) -> tensor<?x2xf32> {
E           ^
E         <stdin>:597:14: error: failed to legalize operation 'memref.alloc'age_class]>, SwiftShader:CPU, {cooperative_matrix_properties_nv = [], max_compute_shared_memory_size = 16384 : i32, max_compute_workgroup_invocations = 128 : i32, max_compute_workgroup_size = dense< tensor<?x12x?x1xf32>, tensor<?x12x?x1xi64>) { tensor<?x12x?x1xf32>, tensor<?x12x?x1xi64>) {
E                      ^
E         <stdin>:21:3: note: called from
E         compilation failed ```

**Comment by MaheshRavishankar** [comment]
This issue needs a bit more infor. Some repro information at least. This is very cryptic error report :)

**Comment by powderluv** [comment]
haha i was just filing the continuation from https://discord.com/channels/689900678990135345/982385246475522098/982387436497821706

Will attach mlir once I finish other failure triage

**Comment by powderluv** [comment]
MLIR: https://storage.googleapis.com/iree-shared-files/nod-perf/anush/9322.mlir
```
$ /opt/conda/envs/testshark/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/opt/conda/envs/testshark/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false pytest_fails/core-reproducer.mlir --iree-llvm-target-cpu-features=host --iree-flow-demote-i64-to-i32 -o test.vmfb
<stdin>:363:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spv.target_env = #spv.target_env<#spv.vce<v1.3, [Shader, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative], [SPV_KHR_storage_buffer_storage_class]>, SwiftShader:CPU, {cooperative_matrix_properties_nv = [], max_compute_shared_memory_size = 16384 : i32, max_compute_workgroup_invocations = 128 : i32, max_compute_workgroup_size = dense<[128, 128, 64]> : vector<3xi32>, subgroup_size = 4 : i32}>}>
<stdin>:21:3: note: called from
<stdin>:363:12: error: failed to serialize executables
<stdin>:21:3: note: called from
<stdin>:597:14: error: failed to legalize operation 'memref.alloc'
<stdin>:21:3: note: called from
<stdin>:597:14: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spv.target_env = #spv.target_env<#spv.vce<v1.3, [Shader, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative], [SPV_KHR_storage_buffer_storage_class]>, SwiftShader:CPU, {cooperative_matrix_properties_nv = [], max_compute_shared_memory_size = 16384 : i32, max_compute_workgroup_invocations = 128 : i32, max_compute_workgroup_size = dense<[128, 128, 64]> : vector<3xi32>, subgroup_size = 4 : i32}>}>
<stdin>:21:3: note: called from
<stdin>:597:14: error: failed to serialize executables
<stdin>:21:3: note: called from
compilation failed ```

**Comment by antiagainst** [comment]
Thomas has https://github.com/google/iree/pull/9326 that addresses the allocation bounds issue. Though there is another issue causing compilation failures (with https://github.com/google/iree/commit/f4189caeea7df562b28476d6162b4e2bc2456a16). 

https://github.com/google/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp#L211-L215

The above pulls in canonicalization patterns that generates new ops even on returning `failure()`:

```
//===-------------------------------------------===//
Processing operation : 'tensor.dim'(0xe476730) {
  %22 = "tensor.dim"(%21, %1) : (tensor<?x?xf32>, index) -> index


  * Pattern (anonymous namespace)::DimOfReifyRankedShapedTypeOpInterface<mlir::tensor::DimOp> : 'tensor.dim -> ()' {
Trying to match "(anonymous namespace)::DimOfReifyRankedShapedTypeOpInterface<mlir::tensor::DimOp>"
    ** Insert  : 'arith.constant'(0xead1960)
    ** Insert  : 'arith.constant'(0xeadec80)
"(anonymous namespace)::DimOfReifyRankedShapedTypeOpInterface<mlir::tensor::DimOp>" result 0
  } -> failure : pattern failed to match
} -> failure : pattern failed to match
//===-------------------------------------------===//
```

This causes the canonicalization framework to continue processing the newly generated ops and cannot converge within 10 times (the default) and then fail.

Changing to `(void)applyPatternsAndFoldGreedily` can make the above input compile. Though we should fix the upstream pattern to avoid generating new ops on failure if possible.

**Comment by powderluv** [comment]
Thanks thanks. Do you have a PR or WIP patch I can try?

**Comment by MaheshRavishankar** [comment]
Yeah it should be fixed upstream. 

> Thomas has #9326 that addresses the allocation bounds issue. Though there is another issue causing compilation failures (with [f4189ca](https://github.com/google/iree/commit/f4189caeea7df562b28476d6162b4e2bc2456a16)).
> 
> [https://github.com/google/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp#L211-L215](https://github.com/google/iree/blob/main/compiler/src/iree/compiler/Codegen/Common/TileAndDistributeToWorkgroupsPass.cpp?rgh-link-date=2022-06-04T03%3A15%3A49Z#L211-L215)
> 
> The above pulls in canonicalization patterns that generates new ops even on returning `failure()`:
> 
> ```
> //===-------------------------------------------===//
> Processing operation : 'tensor.dim'(0xe476730) {
>   %22 = "tensor.dim"(%21, %1) : (tensor<?x?xf32>, index) -> index
> 
> 
>   * Pattern (anonymous namespace)::DimOfReifyRankedShapedTypeOpInterface<mlir::tensor::DimOp> : 'tensor.dim -> ()' {
> Trying to match "(anonymous namespace)::DimOfReifyRankedShapedTypeOpInterface<mlir::tensor::DimOp>"
>     ** Insert  : 'arith.constant'(0xead1960)
>     ** Insert  : 'arith.constant'(0xeadec80)
> "(anonymous namespace)::DimOfReifyRankedShapedTypeOpInterface<mlir::tensor::DimOp>" result 0
>   } -> failure : pattern failed to match
> } -> failure : pattern failed to match
> //===-------------------------------------------===//
> ```
> 
> This causes the canonicalization framework to continue processing the newly generated ops and cannot converge within 10 times (the default) and then fail.
> 
> Changing to `(void)applyPatternsAndFoldGreedily` can make the above input compile. Though we should fix the upstream pattern to avoid generating new ops on failure if possible.

Thats bad! This is the definition of the implicated method https://github.com/llvm/llvm-project/blob/faf43ad7aec2dc530ee0ef162f1274628646954d/mlir/lib/Dialect/MemRef/Transforms/ResolveShapedTypeResultDims.cpp#L123 . It is just one pattern. The two places that return failure after `reifyRankedShape` is called could be asserts. Not sure why this happens... Do you have a repro?

**Comment by antiagainst** [comment]
@powderluv: it's just not checking/surfacing the failures as said. #9333 is the pull request that shows what to change in one way. :)

@MaheshRavishankar: Yes `reifyRankedShape` can always generate new constant ops, which causes the issue. 

Original IR to SPIR-V pipeline so you can invoke `tools/iree-opt -pass-pipeline='hal.executable(hal.executable.variant(iree-codegen-linalg-to-spirv-pipeline))'`:

```mlir
func.func @forward_dispatch_2() {
  %c0_i32 = arith.constant 0 : i32
  %cst = arith.constant 1.000000e+00 : f32
  %cst_0 = arith.constant -1.000000e+04 : f32
  %c0 = arith.constant 0 : index
  %0 = hal.interface.constant.load[0] : i32
  %1 = hal.interface.constant.load[1] : i32
  %2 = hal.interface.constant.load[2] : i32
  %3 = hal.interface.constant.load[3] : i32
  %4 = arith.index_cast %0 : i32 to index
  %5 = arith.index_cast %1 : i32 to index
  %6 = arith.index_cast %2 : i32 to index
  %7 = arith.index_cast %3 : i32 to index
  %8 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:i32>
  %9 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%4) alignment(64) : !flow.dispatch.tensor<readonly:?x1x1x?xf32>{%5, %6}
  %10 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<writeonly:?x?xf32>{%5, %7}
  %11 = flow.dispatch.tensor.load %8, offsets = [], sizes = [], strides = [] : !flow.dispatch.tensor<readonly:i32> -> tensor<i32>
  %12 = linalg.init_tensor [%5, %7] : tensor<?x?xf32>
  %13 = tensor.extract %11[] : tensor<i32>
  %14 = arith.cmpi sgt, %c0_i32, %13 : i32
  %15 = arith.select %14, %13, %c0_i32 : i32
  %16 = arith.index_cast %15 : i32 to index
  %17 = flow.dispatch.tensor.load %9, offsets = [0, 0, 0, %16], sizes = [%5, 1, 1, %7], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:?x1x1x?xf32>{%5, %6} -> tensor<?x?xf32>
  %18 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%17 : tensor<?x?xf32>) outs(%12 : tensor<?x?xf32>) {
  ^bb0(%arg0: f32, %arg1: f32):
    %19 = arith.subf %cst, %arg0 : f32
    %20 = arith.mulf %19, %cst_0 : f32
    linalg.yield %20 : f32
  } -> tensor<?x?xf32>
  flow.dispatch.tensor.store %18, %10, offsets = [0, 0], sizes = [%5, %7], strides = [1, 1] : tensor<?x?xf32> -> !flow.dispatch.tensor<writeonly:?x?xf32>{%5, %7}
  return
}
```

Immediate input to the problematic pattern:

```mlir
func.func @forward_dispatch_2() {
  %c1 = arith.constant 1 : index
  %c0 = arith.constant 0 : index
  %c0_i32 = arith.constant 0 : i32
  %cst = arith.constant 1.000000e+00 : f32
  %cst_0 = arith.constant -1.000000e+04 : f32
  %0 = hal.interface.constant.load[0] : i32
  %1 = hal.interface.constant.load[1] : i32
  %2 = hal.interface.constant.load[2] : i32
  %3 = hal.interface.constant.load[3] : i32
  %4 = arith.index_cast %0 : i32 to index
  %5 = arith.index_cast %1 : i32 to index
  %6 = arith.index_cast %2 : i32 to index
  %7 = arith.index_cast %3 : i32 to index
  %8 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:i32>
  %9 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%4) alignment(64) : !flow.dispatch.tensor<readonly:?x1x1x?xf32>{%5, %6}
  %10 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<writeonly:?x?xf32>{%5, %7}
  %11 = flow.dispatch.tensor.load %8, offsets = [], sizes = [], strides = [] : !flow.dispatch.tensor<readonly:i32> -> tensor<i32>
  %12 = tensor.extract %11[] : tensor<i32>
  %13 = arith.cmpi sgt, %c0_i32, %12 : i32
  %14 = arith.select %13, %12, %c0_i32 : i32
  %15 = arith.index_cast %14 : i32 to index
  %16 = flow.dispatch.tensor.load %9, offsets = [0, 0, 0, %15], sizes = [%5, 1, 1, %7], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:?x1x1x?xf32>{%5, %6} -> tensor<?x?xf32>
  %17 = tensor.dim %16, %c0 : tensor<?x?xf32>
  %18 = tensor.dim %16, %c1 : tensor<?x?xf32>
  %workgroup_id_x = hal.interface.workgroup.id[0] : index
  %workgroup_count_x = hal.interface.workgroup.count[0] : index
  %workgroup_id_y = hal.interface.workgroup.id[1] : index
  %workgroup_count_y = hal.interface.workgroup.count[1] : index
  scf.for %arg0 = %workgroup_id_y to %17 step %workgroup_count_y {
    %19 = affine.apply affine_map<()[s0] -> (s0 * 4)>()[%workgroup_id_x]
    %20 = affine.apply affine_map<()[s0] -> (s0 * 4)>()[%workgroup_count_x]
    scf.for %arg1 = %19 to %18 step %20 {
      %21 = affine.min affine_map<(d0)[s0] -> (-d0 + s0, 4)>(%arg1)[%18]
      %22 = affine.apply affine_map<()[s0, s1] -> (s0 + s1)>()[%arg1, %15]
      %23 = flow.dispatch.tensor.load %9, offsets = [%arg0, 0, 0, %22], sizes = [1, 1, 1, %21], strides = [%c1, 1, 1, %c1] : !flow.dispatch.tensor<readonly:?x1x1x?xf32>{%5, %6} -> tensor<1x?xf32>
      %24 = affine.min affine_map<(d0)[s0] -> (-d0 + s0, 4)>(%arg1)[%18]
      %25 = linalg.init_tensor [1, %24] : tensor<1x?xf32>
      %26 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%23 : tensor<1x?xf32>) outs(%25 : tensor<1x?xf32>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[1, 4], [1, 1]]>} {
      ^bb0(%arg2: f32, %arg3: f32):
        %27 = arith.subf %cst, %arg2 : f32
        %28 = arith.mulf %27, %cst_0 : f32
        linalg.yield %28 : f32
      } -> tensor<1x?xf32>
      flow.dispatch.tensor.store %26, %10, offsets = [%arg0, %arg1], sizes = [1, %24], strides = [%c1, %c1] : tensor<1x?xf32> -> !flow.dispatch.tensor<writeonly:?x?xf32>{%5, %7}
    }
  }
  return
}
```

The issue is with rank-reducing `flow.dispatch.tensor.load` we have in the above. The upstream [pattern](https://github.com/llvm/llvm-project/blob/faf43ad7aec2dc530ee0ef162f1274628646954d/mlir/lib/Dialect/MemRef/Transforms/ResolveShapedTypeResultDims.cpp#L95-L97) obviously does not like that and it expects the same rank.

**Comment by MaheshRavishankar** [comment]
Ok that's a good enough starting point. This should be an easy fix. As I said the failures after calling that method are really asserts. Then it comes down to individual implementation of the interface methods to follow the same principle.

**Comment by antiagainst** [comment]
Thanks to @MaheshRavishankar's #9342, now the top of the tree should work. Closing this. Please re-open if you still see iusses.
