### ISSUE TITLE
error: use of undeclared identifier 'isunordered'; did you mean 'std::isunordered'?

### ISSUE THREAD

**Issue by DavidChan0519** [google/iree#7603]
env:
===
ubuntu 16.04
clang++ 10.01

step:
===
cmake -GNinja -B ../iree-build/ -S . \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DIREE_ENABLE_ASSERTIONS=ON \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DIREE_ENABLE_LLD=ON

cmake --build ../iree-build/

error:
===
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:340:11: error: use of undeclared identifier 'isunordered'; did you mean 'std::isunordered'?
  return (isunordered(lhs, rhs) || (lhs == rhs)) ? 1 : 0;
          ^
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cmath:829:3: note: 'std::isunordered' declared here
  isunordered(float __x, float __y)

**Comment by stellaraccident** [comment]
Thanks for the report. We aren't actively building on that vintage of Ubuntu but would be interested in it working. Would you mind including the full error: specifically, I can't see which source fine that was including the header had the problem (that header is used from not c and c++ so since subtly).

**Comment by DavidChan0519** [comment]
> I can't see which source fine tha

davidcheng@davidcheng-System-Product-Name:~/workspace/repo/github/iree$ cmake --build ../iree-build/
[0/2] Re-checking globbed directories...
[962/4680] Building CXX object third_party/llvm-project/llvm/lib/Analysis/CMakeFiles/LLVMAnalysis.dir/LoopAccessAnalysis.cpp.o
[4669/4680] Building CXX object iree/vm/test/emitc/CMakeFiles/iree_vm_test_emitc_module_test.dir/module_test.cc.o
FAILED: iree/vm/test/emitc/CMakeFiles/iree_vm_test_emitc_module_test.dir/module_test.cc.o
/home/davidcheng/workspace/repo/github/clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang++ -DIREE_HAVE_EMITC_DIALECT -isystem /home/davidcheng/workspace/repo/github/iree -isystem /home/davidcheng/workspace/repo/github/iree-build -isystem /home/davidcheng/workspace/repo/github/iree/third_party/googletest/googlemock/include -isystem /home/davidcheng/workspace/repo/github/iree/third_party/googletest/googlemock -isystem /home/davidcheng/workspace/repo/github/iree/third_party/googletest/googletest/include -isystem /home/davidcheng/workspace/repo/github/iree/third_party/googletest/googletest -O2 -g  -fPIE -fvisibility=hidden -fno-rtti -fno-exceptions -Werror -Wall -Wno-ambiguous-member-template -Wno-char-subscripts -Wno-deprecated-declarations -Wno-extern-c-compat -Wno-gnu-alignof-expression -Wno-gnu-variable-sized-type-not-at-end -Wno-ignored-optimization-argument -Wno-invalid-offsetof -Wno-invalid-source-encoding -Wno-mismatched-tags -Wno-pointer-sign -Wno-reserved-user-defined-literal -Wno-return-type-c-linkage -Wno-self-assign-overloaded -Wno-sign-compare -Wno-signed-unsigned-wchar -Wno-strict-overflow -Wno-trigraphs -Wno-unknown-pragmas -Wno-unknown-warning-option -Wno-unused-command-line-argument -Wno-unused-const-variable -Wno-unused-function -Wno-unused-local-typedef -Wno-unused-private-field -Wno-user-defined-warnings -Wctad-maybe-unsupported -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wformat-security -Wgnu-redeclared-enum -Wimplicit-fallthrough -Winfinite-recursion -Wliteral-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety -Wthread-safety-beta -Wunused-comparison -Wvla -std=gnu++14 -MD -MT iree/vm/test/emitc/CMakeFiles/iree_vm_test_emitc_module_test.dir/module_test.cc.o -MF iree/vm/test/emitc/CMakeFiles/iree_vm_test_emitc_module_test.dir/module_test.cc.o.d -o iree/vm/test/emitc/CMakeFiles/iree_vm_test_emitc_module_test.dir/module_test.cc.o -c /home/davidcheng/workspace/repo/github/iree/iree/vm/test/emitc/module_test.cc
In file included from /home/davidcheng/workspace/repo/github/iree/iree/vm/test/emitc/module_test.cc:11:
In file included from /home/davidcheng/workspace/repo/github/iree-build/iree/vm/test/emitc/arithmetic_ops.h:2:
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:340:11: error: use of undeclared identifier 'isunordered'; did you mean 'std::isunordered'?
  return (isunordered(lhs, rhs) || (lhs == rhs)) ? 1 : 0;
          ^
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cmath:829:3: note: 'std::isunordered' declared here
  isunordered(float __x, float __y)
  ^
In file included from /home/davidcheng/workspace/repo/github/iree/iree/vm/test/emitc/module_test.cc:11:
In file included from /home/davidcheng/workspace/repo/github/iree-build/iree/vm/test/emitc/arithmetic_ops.h:2:
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:346:11: error: use of undeclared identifier 'isunordered'; did you mean 'std::isunordered'?
  return (isunordered(lhs, rhs) || (lhs != rhs)) ? 1 : 0;
          ^
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cmath:829:3: note: 'std::isunordered' declared here
  isunordered(float __x, float __y)
  ^
In file included from /home/davidcheng/workspace/repo/github/iree/iree/vm/test/emitc/module_test.cc:11:
In file included from /home/davidcheng/workspace/repo/github/iree-build/iree/vm/test/emitc/arithmetic_ops.h:2:
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:349:10: error: use of undeclared identifier 'isless'; did you mean 'std::isless'?
  return isless(lhs, rhs) ? 1 : 0;
         ^
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cmath:751:3: note: 'std::isless' declared here
  isless(float __x, float __y)
  ^
In file included from /home/davidcheng/workspace/repo/github/iree/iree/vm/test/emitc/module_test.cc:11:
In file included from /home/davidcheng/workspace/repo/github/iree-build/iree/vm/test/emitc/arithmetic_ops.h:2:
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:352:11: error: use of undeclared identifier 'isunordered'; did you mean 'std::isunordered'?
  return (isunordered(lhs, rhs) || isless(lhs, rhs)) ? 1 : 0;
          ^
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cmath:829:3: note: 'std::isunordered' declared here
  isunordered(float __x, float __y)
  ^
In file included from /home/davidcheng/workspace/repo/github/iree/iree/vm/test/emitc/module_test.cc:11:
In file included from /home/davidcheng/workspace/repo/github/iree-build/iree/vm/test/emitc/arithmetic_ops.h:2:
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:352:36: error: use of undeclared identifier 'isless'; did you mean 'std::isless'?
  return (isunordered(lhs, rhs) || isless(lhs, rhs)) ? 1 : 0;
                                   ^
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cmath:751:3: note: 'std::isless' declared here
  isless(float __x, float __y)
  ^
In file included from /home/davidcheng/workspace/repo/github/iree/iree/vm/test/emitc/module_test.cc:11:
In file included from /home/davidcheng/workspace/repo/github/iree-build/iree/vm/test/emitc/arithmetic_ops.h:2:
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:355:10: error: use of undeclared identifier 'islessequal'; did you mean 'std::islessequal'?
  return islessequal(lhs, rhs) ? 1 : 0;
         ^
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cmath:777:3: note: 'std::islessequal' declared here
  islessequal(float __x, float __y)
  ^
In file included from /home/davidcheng/workspace/repo/github/iree/iree/vm/test/emitc/module_test.cc:11:
In file included from /home/davidcheng/workspace/repo/github/iree-build/iree/vm/test/emitc/arithmetic_ops.h:2:
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:358:11: error: use of undeclared identifier 'isunordered'; did you mean 'std::isunordered'?
  return (isunordered(lhs, rhs) || islessequal(lhs, rhs)) ? 1 : 0;
          ^
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cmath:829:3: note: 'std::isunordered' declared here
  isunordered(float __x, float __y)
  ^
In file included from /home/davidcheng/workspace/repo/github/iree/iree/vm/test/emitc/module_test.cc:11:
In file included from /home/davidcheng/workspace/repo/github/iree-build/iree/vm/test/emitc/arithmetic_ops.h:2:
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:358:36: error: use of undeclared identifier 'islessequal'; did you mean 'std::islessequal'?
  return (isunordered(lhs, rhs) || islessequal(lhs, rhs)) ? 1 : 0;
                                   ^
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cmath:777:3: note: 'std::islessequal' declared here
  islessequal(float __x, float __y)
  ^
In file included from /home/davidcheng/workspace/repo/github/iree/iree/vm/test/emitc/module_test.cc:11:
In file included from /home/davidcheng/workspace/repo/github/iree-build/iree/vm/test/emitc/arithmetic_ops.h:2:
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:361:10: error: use of undeclared identifier 'isnan'
  return isnan(operand) ? 1 : 0;
         ^
9 errors generated.
[4674/4680] Building CXX object iree/vm/CMakeFiles/iree_vm_bytecode_module_test.dir/bytecode_dispatch_test.cc.o
ninja: build stopped: subcommand failed.

**Comment by stellaraccident** [comment]
Thanks. I can look into a patch tomorrow, but I suspect that adding a `using namespace std;` in ree/iree/vm/test/emitc/module_test.cc after the standard headers would unblock.

This one is weird because it is a C++ test of a header that is primarily used by C code, so the right interop incantation is needed.

**Comment by stellaraccident** [comment]
Or just in an `#def __cplusplus__` in the header in question

**Comment by DavidChan0519** [comment]
> #ifdef __cplusplus__

ok , I will have a try

**Comment by DavidChan0519** [comment]
> Or just in an `#ifdef __cplusplus__` in the header in question

Unresolved , there will be another problem produced

**Comment by DavidChan0519** [comment]
Is there a docker environment provided?  Maybe it is easier to build from source

**Comment by stellaraccident** [comment]
I was just going to ask you if you had a docker environment for ubuntu 16.04? I'm having trouble getting tools that still install on that OS (specifically, I can only find up to clang-8).

Our CI has docker with all of the tools (and a bunch of other stuff), but I also routinely build on a fresh Ubuntu 20.04+ docker container using the instructions and since that works out of the box, we haven't yet found the need to host a developer focused docker image.

Update:
I have been able to repro your problem on a fresh Ubuntu 16.04 with clang-8 (after a fashion). Let me see if I can identify a fix.

**Comment by DavidChan0519** [comment]
> I was just going to ask you if you had a docker environment for ubuntu 16.04? I'm having trouble getting tools that still install on that OS (specifically, I can only find up to clang-8).
> 
> Our CI has docker with all of the tools (and a bunch of other stuff), but I also routinely build on a fresh Ubuntu 20.04+ docker container using the instructions and since that works out of the box, we haven't yet found the need to host a developer focused docker image.
> 
> Update: I have been able to repro your problem on a fresh Ubuntu 16.04 with clang-8 (after a fashion). Let me see if I can identify a fix.

thanks!

**Comment by stellaraccident** [comment]
Posted a fix above. Waiting for CI to tell me whether it broke any others.

For posterity, I got a working Ubuntu 16.04 setup with roughly the following, from a stock docker image:

```
    4  apt update
    6  apt install wget
    7  cd
    8  wget https://github.com/Kitware/CMake/releases/download/v3.22.0-rc2/cmake-3.22.0-rc2-linux-x86_64.sh
    9  bash cmake-3.22.0-rc2-linux-x86_64.sh
   10  apt install ninja-build
   21  printf "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main" | tee /etc/apt/sources.list.d/llvm-toolchain-xenial-12.list
   23  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
   24  apt update
   25  apt install apt-transport-https
   30  apt install llvm-8
   45  apt install clang-8
   48  ./cmake-3.22.0-rc2-linux-x86_64/bin/cmake -GNinja -Bbuild -S /work/iree -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8
   49  cd build/
   50  ninja
   51  ctest .
```

Had some test failures due to missing vulkan, which is fine.

**Comment by DavidChan0519** [comment]
> from a stock docker image

thanks for your quick response and support!

**Comment by DavidChan0519** [comment]
https://github.com/stellaraccident/iree/commit/aa4848460a2ecee199c9620ea796df2aa17a3abc 
this patch works fine for me. Resolved
