### ISSUE TITLE
Colab notebook failures after DeviceArray changes

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#8253]
Started failing since https://github.com/google/iree/pull/8206
CI logs: https://buildkite.com/iree/iree-samples/builds/236#a66ab4d1-7902-4b0d-ab30-1ecd67263484

Notebooks are stored at https://github.com/google/iree/tree/main/colab

edge_detection.ipynb fails at 
```python
  edges = iree_function(args...)  # DeviceArray
  axs[1].imshow(edges.reshape(128, 128), cmap="gray")

# AttributeError: 'DeviceArray' object has no attribute 'reshape'
```

resnet.ipynb fails at
```python
iree_result = iree_module.predict(input_data)  # DeviceArray
tf.keras.applications.resnet50.decode_predictions(result, top=3)[0]

[2022-02-05T00:08:21Z] --> 158   for pred in preds:
[2022-02-05T00:08:21Z]     159     top_indices = pred.argsort()[-top:][::-1]
[2022-02-05T00:08:21Z]     160     result = [tuple(CLASS_INDEX[str(i)]) + (pred[i],) for i in top_indices]
[2022-02-05T00:08:21Z]
[2022-02-05T00:08:21Z] TypeError: 'DeviceArray' object is not iterable
```

tflite_text_classification.ipynb fails at
```python
[2022-02-05T00:09:49Z]      12   result = invoke_text_classification(tokenize_input(text))
[2022-02-05T00:09:49Z] ---> 13   interpret_output(result[0])
[2022-02-05T00:09:49Z]
[2022-02-05T00:09:49Z] TypeError: 'DeviceArray' object is not subscriptable
```

As needed, notebooks can be tested individually with https://github.com/google/iree/blob/main/build_tools/testing/run_python_notebook.sh or as a set with https://github.com/google/iree/blob/main/colab/test_notebooks.py (note the expected failure - that will still log errors to console that are okay to ignore).

If changes to the notebooks themselves are needed, you can edit the .ipynb files directly (carefully) or follow the steps at https://github.com/google/iree/tree/main/colab#working-with-github. I can also help with that part.

**Comment by ScottTodd** [comment]
Oh, and the notebooks embed calls to `python -m pip install iree-compiler iree-runtime iree-tools-tf -f https://github.com/google/iree/releases` (or similar)... so they aren't really meant for running with local python packages. The test scripts also create new venvs... so maybe just ignore the comments about testing the notebooks :P

**Comment by ScottTodd** [comment]
Colab notebooks and the other sample tests are passing again as of https://github.com/google/iree/releases/tag/candidate-20220302.64 🎉 
https://buildkite.com/iree/iree-samples/builds/262
