### PR TITLE
Rework the way std math ops are used from C and C++.

### LINKED ISSUE #7603: error: use of undeclared identifier 'isunordered'; did you mean 'std::isunordered'?
env:
===
ubuntu 16.04
clang++ 10.01

step:
===
cmake -GNinja -B ../iree-build/ -S . \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DIREE_ENABLE_ASSERTIONS=ON \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DIREE_ENABLE_LLD=ON

cmake --build ../iree-build/

error:
===
/home/davidcheng/workspace/repo/github/iree/iree/vm/ops.h:340:11: error: use of undeclared identifier 'isunordered'; did you mean 'std::isunordered'?
  return (isunordered(lhs, rhs) || (lhs == rhs)) ? 1 : 0;
          ^
/usr/lib/gcc/x86_64-linux-gnu/5.5.0/../../../../include/c++/5.5.0/cmath:829:3: note: 'std::isunordered' declared here
  isunordered(float __x, float __y)

### PR DESCRIPTION
**Pull request by stellaraccident**
This attempts to do the right thing from a C/C++ namespace perspective and then works around brokenness in old versions of libstdc++ that keep us from doing the complete right thing.

Fixes #7603

### CODE REVIEW

**Review by marbre — APPROVED** [review]
I don't really like that we need a fix because of a test written in C++. Nevertheless, I really like the fix itself!

**Review by benvanik — CHANGES_REQUESTED** [review]
Yeah we don't want this this C++ in there - the file should be pure C and these kind of changes make it really brittle - we'll just be broken in different places and play whackamole as with the complexity of this stuff we'll never be able to safely make changes.

The root of the issue is that emitc generates all its code in a .h - it should only declare a function in the .h and all the rest should be in a .c that's compiled independently. No C++ file should ever include this header.

Since this is just a low-level test for emitc until we fix that a user hitting the issue can just disable emitc with the cmake flag.

**Comment by benvanik** [comment]
Another thing to try, since you have a setup you can test, is moving the header in the test - right now it's at the top before any C++ includes, but it may play better if it is below them: https://github.com/google/iree/blob/89e9530b79e7946e04ccde9b0ac226a3f98dbffa/iree/samples/emitc_modules/add_module_test.cc

**Comment by benvanik** [comment]
(here's an issue for making emitc modules safe to use: https://github.com/google/iree/issues/7605)

**Comment by stellaraccident** [comment]
If this isn't supposed to be a thing we do, I'll just add a `using namespace std` to that one test. That's what I had, but I convinced myself this was a real use case and did a real fix. If it's not, I'll just do the simple thing until emitc can be layered as desired.

**Comment by stellaraccident** [comment]
PTAL

**Review by benvanik — APPROVED** [review]
