### ISSUE TITLE
Windows Bazel builds of LLVM are failing

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#3756]
**Describe the bug**
Core parts of the project fail to build on my Windows machine using Bazel, starting recently:
```
ERROR: D:/tmp/bzlroot/3mtfpusj/external/llvm-project/llvm/BUILD:1665:16: C++ compilation of rule '@llvm-project//llvm:X86UtilsAndDesc' failed (Exit 2)
bazel-out/x64_windows-opt/bin/external/llvm-project/llvm/lib/Target/X86\X86GenInstrInfo.inc(37938): fatal error C1091: compiler limit: string exceeds 65535 bytes in length
Target @llvm-project//llvm:X86UtilsAndDesc failed to build
```

**To Reproduce**
```
λ git checkout main
λ git pull
λ git submodule update
// originally found with:
λ bazel build iree/tools:iree-opt
// somewhat minimal:
λ bazel build @llvm-project//llvm:X86UtilsAndDesc
```

**Additional context**
`git bisect` pointed to https://github.com/google/iree/commit/59125f7498f6af7166b7dc4c04d94088e4fd8fa4

`D:\dev\scratch\bisect_command.sh`:
```
git submodule update
bazel build @llvm-project//llvm:X86UtilsAndDesc

```

Running bisect:
```
λ git bisect start --first-parent
λ git bisect bad
λ git bisect good 2097c3ec30d878c5274b0be8fbb3fe8a11834e18
λ git bisect run bash -v D:\dev\scratch\bisect_command.sh
...
FAILED: Build did NOT complete successfully
59125f7498f6af7166b7dc4c04d94088e4fd8fa4 is the first bad commit
commit 59125f7498f6af7166b7dc4c04d94088e4fd8fa4
Merge: d4418d9d 306ca0a0
Author: Geoffrey Martin-Noble <gcmn@google.com>
Date:   Thu Oct 29 12:38:25 2020 -0700

    Merge google -> main (#3659)
```

**Comment by ScottTodd** [comment]
This particular issue is fixed now.
